2019-04-25 13:04:10,888 [DEBUG] Using GPU 0
2019-04-25 13:04:10,914 [DEBUG] CACHEDIR=/home/thinh/.cache/matplotlib
2019-04-25 13:04:10,915 [DEBUG] Using fontManager instance from /home/thinh/.cache/matplotlib/fontlist-v300.json
2019-04-25 13:04:10,965 [DEBUG] Loaded backend agg version unknown.
2019-04-25 13:04:12,116 [INFO] ==> VIDEO_ROOT_PATH/UCSD_ped1/testing_h5_t0/UCSD_ped1_14.h5
2019-04-25 13:04:12,116 [DEBUG] Predicting using logs/UCSD_ped1/jobs/f5846318-6990-4622-b584-ececf33a54d7/model_snapshot_e298_0.003159.h5
2019-04-25 13:04:12,891 [CRITICAL] Uncaught exception
Traceback (most recent call last):
  File "/home/thinh/github/anomaly-detection-and-localization/start_test.py", line 73, in <module>
    visualize_score=True, visualize_frame=True)
  File "/home/thinh/github/anomaly-detection-and-localization/classifier.py", line 490, in test
    res = stripe_predict(temporal_model, X_test, 10)
  File "/home/thinh/github/anomaly-detection-and-localization/classifier.py", line 442, in stripe_predict
    ret_arr.append(((combine_stripe(predicted_batch, stripe_h) * combine_stripe(predicted_batch2, stripe_h - 7) - norm_prediction)**2))
ValueError: operands could not be broadcast together with shapes (160,240) (1,160,240,1) 
