2019-04-11 13:18:26,384 [DEBUG] Using GPU 0
2019-04-11 13:18:26,432 [DEBUG] CACHEDIR=/home/thinh/.cache/matplotlib
2019-04-11 13:18:26,435 [DEBUG] Using fontManager instance from /home/thinh/.cache/matplotlib/fontlist-v300.json
2019-04-11 13:18:26,553 [DEBUG] Loaded backend agg version unknown.
2019-04-11 13:18:28,520 [INFO] ==> VIDEO_ROOT_PATH/UCSD_ped1/testing_h5_t0/UCSD_ped1_01.h5
2019-04-11 13:18:28,520 [DEBUG] Predicting using logs/UCSD_ped1/jobs/db291bbf-55e9-40fd-b01f-43b4e474ec55/model_snapshot_e010_0.002689.h5
2019-04-11 13:18:28,520 [CRITICAL] Uncaught exception
Traceback (most recent call last):
  File "/home/thinh/Downloads/pycharm-community-2018.3.5/helpers/pydev/pydevd.py", line 1741, in <module>
    main()
  File "/home/thinh/Downloads/pycharm-community-2018.3.5/helpers/pydev/pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/thinh/Downloads/pycharm-community-2018.3.5/helpers/pydev/pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/thinh/Downloads/pycharm-community-2018.3.5/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/thinh/github/anomaly-detection-and-localization/start_test.py", line 63, in <module>
    visualize_score=True, visualize_frame=True)
  File "/home/thinh/github/anomaly-detection-and-localization/classifier.py", line 387, in test
    X_test = np.load(os.path.join(video_root_path, '{0}/testing_frames_{1:02d}.npy'.format(dataset, videoid+1)))
  File "/home/thinh/miniconda3/envs/ano/lib/python3.6/site-packages/numpy/lib/npyio.py", line 415, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'VIDEO_ROOT_PATH/UCSD_ped1/testing_frames_01.npy'
