2019-04-18 16:50:42,229 [DEBUG] Using GPU 0
2019-04-18 16:50:42,281 [DEBUG] CACHEDIR=/home/thinh/.cache/matplotlib
2019-04-18 16:50:42,284 [DEBUG] Using fontManager instance from /home/thinh/.cache/matplotlib/fontlist-v300.json
2019-04-18 16:50:42,413 [DEBUG] Loaded backend agg version unknown.
2019-04-18 16:50:44,503 [INFO] ==> VIDEO_ROOT_PATH/UCSD_ped1/testing_h5_t0/UCSD_ped1_01.h5
2019-04-18 16:50:44,503 [DEBUG] Predicting using logs/UCSD_ped1/jobs/f5846318-6990-4622-b584-ececf33a54d7/model_snapshot_e298_0.003159.h5
2019-04-18 16:51:05,464 [CRITICAL] Uncaught exception
Traceback (most recent call last):
  File "/home/thinh/Downloads/pycharm-community-2018.3.5/helpers/pydev/pydevd.py", line 1741, in <module>
    main()
  File "/home/thinh/Downloads/pycharm-community-2018.3.5/helpers/pydev/pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/thinh/Downloads/pycharm-community-2018.3.5/helpers/pydev/pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/thinh/Downloads/pycharm-community-2018.3.5/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/thinh/github/anomaly-detection-and-localization/start_test.py", line 73, in <module>
    visualize_score=True, visualize_frame=True)
  File "/home/thinh/github/anomaly-detection-and-localization/classifier.py", line 456, in test
    res = stripe_predict(temporal_model, X_test, 3)
  File "/home/thinh/github/anomaly-detection-and-localization/classifier.py", line 408, in stripe_predict
    save_color_image(combine_stripe(norm_prediction - predicted_batch, stripe_h), os.path.join("temp2", "fc{0}.jpg".format(str(i))))
  File "/home/thinh/github/anomaly-detection-and-localization/visualization.py", line 22, in save_color_image
    fig, ax = plt.subplot(1)
  File "/home/thinh/miniconda3/envs/ano/lib/python3.6/site-packages/matplotlib/pyplot.py", line 1084, in subplot
    a = fig.add_subplot(*args, **kwargs)
  File "/home/thinh/miniconda3/envs/ano/lib/python3.6/site-packages/matplotlib/figure.py", line 1335, in add_subplot
    "three-digit number, not {}".format(args[0]))
ValueError: Integer subplot specification must be a three-digit number, not 1
