2019-05-29 22:15:34,303 [DEBUG] Using GPU 0
2019-05-29 22:15:34,356 [DEBUG] CACHEDIR=/home/thinh/.cache/matplotlib
2019-05-29 22:15:34,359 [DEBUG] Using fontManager instance from /home/thinh/.cache/matplotlib/fontlist-v300.json
2019-05-29 22:15:34,486 [DEBUG] Loaded backend agg version unknown.
2019-05-29 22:15:35,610 [DEBUG] update_title_pos
2019-05-29 22:15:35,621 [DEBUG] findfont: Matching :family=sans-serif:style=normal:variant=normal:weight=normal:stretch=normal:size=10.0 to DejaVu Sans ('/home/thinh/miniconda3/envs/ano/lib/python3.6/site-packages/matplotlib/mpl-data/fonts/ttf/DejaVuSans.ttf') with score of 0.050000.
2019-05-29 22:15:49,685 [DEBUG] update_title_pos
2019-05-29 22:16:11,192 [INFO] ==> VIDEO_ROOT_PATH/UCSD_ped1/testing_h5_t0/UCSD_ped1_01.h5
2019-05-29 22:16:11,192 [DEBUG] Predicting using logs/UCSD_ped1/jobs/f5846318-6990-4622-b584-ececf33a54d7/model_snapshot_e298_0.003159.h5
2019-05-29 22:16:19,385 [CRITICAL] Uncaught exception
Traceback (most recent call last):
  File "/home/thinh/Downloads/pycharm-community-2018.3.5/helpers/pydev/pydevd.py", line 1741, in <module>
    main()
  File "/home/thinh/Downloads/pycharm-community-2018.3.5/helpers/pydev/pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/thinh/Downloads/pycharm-community-2018.3.5/helpers/pydev/pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/thinh/Downloads/pycharm-community-2018.3.5/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/thinh/github/anomaly-detection-and-localization/start_test.py", line 79, in <module>
    visualize_score=True, visualize_frame=True)
  File "/home/thinh/github/anomaly-detection-and-localization/classifier.py", line 709, in test
    total_err = fusion_matrix(t_err, s_err, type="mul")
  File "/home/thinh/github/anomaly-detection-and-localization/classifier.py", line 616, in fusion_matrix
    return normalize(matrixA*matrixB)
ValueError: operands could not be broadcast together with shapes (196,) (200,) 
