2019-04-18 15:25:58,428 [DEBUG] Using GPU 0
2019-04-18 15:25:58,478 [DEBUG] CACHEDIR=/home/thinh/.cache/matplotlib
2019-04-18 15:25:58,481 [DEBUG] Using fontManager instance from /home/thinh/.cache/matplotlib/fontlist-v300.json
2019-04-18 15:25:58,605 [DEBUG] Loaded backend agg version unknown.
2019-04-18 15:26:00,682 [INFO] ==> VIDEO_ROOT_PATH/UCSD_ped1/testing_h5_t0/UCSD_ped1_01.h5
2019-04-18 15:26:00,682 [DEBUG] Predicting using logs/UCSD_ped1/jobs/f5846318-6990-4622-b584-ececf33a54d7/model_snapshot_e298_0.003159.h5
2019-04-18 15:26:06,634 [CRITICAL] Uncaught exception
Traceback (most recent call last):
  File "/home/thinh/Downloads/pycharm-community-2018.3.5/helpers/pydev/pydevd.py", line 1741, in <module>
    main()
  File "/home/thinh/Downloads/pycharm-community-2018.3.5/helpers/pydev/pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/thinh/Downloads/pycharm-community-2018.3.5/helpers/pydev/pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/thinh/Downloads/pycharm-community-2018.3.5/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/thinh/github/anomaly-detection-and-localization/start_test.py", line 73, in <module>
    visualize_score=True, visualize_frame=True)
  File "/home/thinh/github/anomaly-detection-and-localization/classifier.py", line 442, in test
    res = stripe_predict(temporal_model, X_test, 2)
  File "/home/thinh/github/anomaly-detection-and-localization/classifier.py", line 396, in stripe_predict
    image_side_side(np.squeeze(predicted_batch), np.squeeze(norm_prediction - predicted_batch),save_name)
  File "/home/thinh/github/anomaly-detection-and-localization/visualization.py", line 12, in image_side_side
    fig.tight_layout(pad=0.0, w_pad=0.0, h_pad=0.0)
  File "/home/thinh/miniconda3/envs/ano/lib/python3.6/site-packages/matplotlib/figure.py", line 2373, in tight_layout
    renderer = get_renderer(self)
  File "/home/thinh/miniconda3/envs/ano/lib/python3.6/site-packages/matplotlib/tight_layout.py", line 228, in get_renderer
    renderer = canvas.get_renderer()
  File "/home/thinh/miniconda3/envs/ano/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 417, in get_renderer
    self.renderer = RendererAgg(w, h, self.figure.dpi)
  File "/home/thinh/miniconda3/envs/ano/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 87, in __init__
    self._renderer = _RendererAgg(int(width), int(height), dpi)
ValueError: Image size of 500x200000 pixels is too large. It must be less than 2^16 in each direction.
