2019-04-23 14:26:39,881 [DEBUG] Using GPU 0
2019-04-23 14:26:39,930 [DEBUG] CACHEDIR=/home/thinh/.cache/matplotlib
2019-04-23 14:26:39,933 [DEBUG] Using fontManager instance from /home/thinh/.cache/matplotlib/fontlist-v300.json
2019-04-23 14:26:40,056 [DEBUG] Loaded backend agg version unknown.
2019-04-23 14:26:42,054 [INFO] ==> VIDEO_ROOT_PATH/UCSD_ped1/testing_h5_t0/UCSD_ped1_03.h5
2019-04-23 14:26:42,054 [DEBUG] Predicting using logs/UCSD_ped1/jobs/f5846318-6990-4622-b584-ececf33a54d7/model_snapshot_e298_0.003159.h5
2019-04-23 14:27:19,220 [INFO] Dataset UCSD_ped1: Overall PR-AUC = 0.56%
2019-04-23 14:27:26,654 [CRITICAL] Uncaught exception
Traceback (most recent call last):
  File "/home/thinh/Downloads/pycharm-community-2018.3.5/helpers/pydev/pydevd.py", line 1741, in <module>
    main()
  File "/home/thinh/Downloads/pycharm-community-2018.3.5/helpers/pydev/pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/thinh/Downloads/pycharm-community-2018.3.5/helpers/pydev/pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/thinh/Downloads/pycharm-community-2018.3.5/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/thinh/github/anomaly-detection-and-localization/start_test.py", line 73, in <module>
    visualize_score=True, visualize_frame=True)
  File "/home/thinh/github/anomaly-detection-and-localization/classifier.py", line 468, in test
    calc_precision_recall_per_video_pixel(logger, dataset, videoid, save_path, res)
  File "/home/thinh/github/anomaly-detection-and-localization/classifier.py", line 349, in calc_precision_recall_per_video_pixel
    plt.title('{0} PR-AUC: {1:.3f}'.format(dataset, auc))
TypeError: unsupported format string passed to function.__format__
